name: Check Pull Request
on: pull_request

jobs:
  check_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR target branch is ok
        run: |
          branch_name=${GITHUB_HEAD_REF}
          echo "pr branch name: $branch_name"
          regex="^(feature|fix|revert)\/[a-zA-Z0-9_-]*$"
          if [[ "$branch_name" =~ $regex ]]; then
            echo "Branch name matches the first regex pattern."
          else
            echo "Branch name does not match any regex. Exiting..."
            exit 1
          fi
        shell: bash
