name: Check Commit Message
on: push

jobs:
  check_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Check if commit message is properly formatted
        run: |
          commit_message="${{github.event.head_commit.message}}"
          echo "Commit message: $commit_message"
          regex="^(feat|fix)\([a-zA-Z0-9\ \-_]*\): .*$"
          if [[ "$commit_message" =~ $regex ]]; then
            echo "The commit message is well formatted."
          else
            echo "The commit message is not well formatted."
            exit 1
          fi
        shell: bash
